<a href="https://colab.research.google.com/github/Michu041977/Michal_pub/blob/main/plik1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install


TensorFlow version: 2.17.1


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Dla każdego przykładu model zwraca wektor wyników logit lub log-odds , po jednym dla każdej klasy.

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.30784872,  0.00455337,  0.26761577,  0.7174302 ,  0.17106256,
         0.19421035,  0.32657433, -0.05295785,  0.05858417, -0.41901827]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()


array([[0.1117483 , 0.08251282, 0.10734158, 0.16831386, 0.09746202,
        0.09974436, 0.11386057, 0.07790129, 0.08709369, 0.0540215 ]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [11]:
loss_fn(y_train[:1], predictions).numpy()


2.3051448

In [12]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [10]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8631 - loss: 0.4713
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.9558 - loss: 0.1512
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9664 - loss: 0.1121
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9728 - loss: 0.0892
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9769 - loss: 0.0726


Metoda Model.evaluate sprawdza wydajność modeli, zwykle na „ zestawie walidacyjnym ” lub „ zestawie testowym ”.

In [13]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 1s - 3ms/step - accuracy: 0.9773 - loss: 0.0772


[0.07719878852367401, 0.9772999882698059]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [15]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.27740583e-08, 4.38216397e-09, 1.41307385e-06, 1.65412148e-05,
        1.18447446e-10, 1.28295827e-08, 7.69981138e-14, 9.99973774e-01,
        4.64822051e-07, 7.80108985e-06],
       [1.61431231e-07, 1.03311409e-04, 9.99887705e-01, 4.51975711e-06,
        6.29222477e-13, 2.85329497e-06, 6.35306037e-07, 2.73891292e-11,
        8.02234695e-07, 6.38407036e-11],
       [7.59147667e-07, 9.98580694e-01, 2.16444787e-05, 4.76932973e-06,
        1.18647047e-04, 7.46775777e-06, 2.53364979e-05, 1.13176403e-03,
        1.04216015e-04, 4.71054318e-06],
       [9.99934793e-01, 3.03072056e-08, 1.41738828e-05, 1.89345783e-07,
        1.08430598e-07, 2.88136812e-06, 1.15979901e-05, 3.53883916e-05,
        2.92707742e-08, 7.71725581e-07],
       [6.47817160e-07, 3.19170534e-09, 2.28776798e-06, 5.15801135e-09,
        9.93633866e-01, 5.30648236e-08, 1.48986237e-06, 3.10559153e-05,
        1.56442366e-06, 6.32903492e-03]], dtype=float32)>